### ISSUE TITLE
[Bug] Conversation controls are misplaced

### ISSUE THREAD

**Issue by franckflo** [CristianVasile23/conversation-hud#15]
Hi, thanks for this Module that is really nice for theater of the mind encounters!

I noticed a bug. When a conversation is running, I couldn't s see the little icons to save/minimize/hide the conversation I could see in your demo. It turns out, on my setup they are lined up all the way to the right of the page, not on the left of the sidebar as in your demo.  I have a couple suggestions to fix that issue:

- Could it be possible to have it look at the CSS for the sidebar and the Custom CSS if that module is installed, and have the icons be slightly to the left of that value. Here is the code in the CSS that defines the width of the sidebar:

`#sidebar {
  width: 400px !important;
  background-size: 400px 100% !important;`

- Alternatively, an input in the module's settings allowing the GM to define how far from the right side of the screen the icons are located would work too!

Thanks !!

**Comment by CristianVasile23** [comment]
Hi there! Thanks for the interest in the module!

As to the issue, that is some strange behavior and I don't really know why that is happening. The way the buttons are placed should be responsive depending on size of the sidebar. They shouldn't appear all the way to the right unless something changes the layout of the interface, which is why I think your issue appears due to the custom CSS you mentioned.

But just to make sure, if you turn off the Custom CSS module (or delete the rule mentioned above I guess), does the issue still appear?

**Comment by franckflo** [comment]
Hi, that was a good idea, however disabling Custom CSS did not help so I guess it’s something else. I’m going to run a Find the Culprit test run and will report if I find another module causing a conflict.

**Comment by CristianVasile23** [comment]
Yep, sound great, keep me posted.

In the meantime, I will also work on adding an option to change the placement of the buttons as I have some ideas for alternative positions that should avoid this issue.

**Comment by franckflo** [comment]
Hi, FTC found the conflicting module: Mythic UI Rebirth. It's a UI mod for playing antiquity-based games. I'm running Odyssey of the Dragonlords right now, so it'd be nice if we could find a way for both modules to work together. Thanks!

**Comment by CristianVasile23** [comment]
Great, thanks for letting me know what the cause of the problem is. I will investigate the module and see if I can come up with a solution that fixes the problem. The fix will probably come either this weekend or sometimes next week when I also add some additional features to the module.

**Comment by franckflo** [comment]
That's great, thanks a lot for your help!

**Comment by CristianVasile23** [comment]
I have added a toggle that should fix the issue you were having in release 4.1.0. By default it is off so you will have to turn it on in the module settings.

The issue was caused by the way most of the custom UI handle the sidebar position. I have no idea why fixed positioning is used as it "breaks" the layout positioning in the page. Fixed positioning shouldn't be used in this case, maybe this is a remnant from the older versions of Foundry, but in the current version I see no reason for fixed positioning to be used for the sidebar.

What the toggle does is to restore the default positioning of the sidebar, thus fixing the overlap. It should work with most of the custom UI modules (I have tested a few), but it might cause some weird behavior on some. Thankfully, Mythic UI seems to work without any issues as far as I can tell. That said, if you encounter any problems, feel free to contact me (here or on discord). And who knows, maybe the with V11 and the UI customization options introduced, maybe this issue will be solved in future releases of the UI modules.

**Comment by franckflo** [comment]
Hi there. I upgraded to 4.1.0 and It seems the problem is still there with Mythic UI enabled. I also disabled Custom CSS also to make sure that wasn't the issue: No dice. Sorry for the bad news!

**Comment by CristianVasile23** [comment]
Have you enabled the fix in the settings? Because by default it is disabled.

**Comment by franckflo** [comment]
Duh, yes that fixed it :). Thanks a lot!
